# Generated by Django 6.0.2 on 2026-06-22 17:36

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoricalRekorLogEntry",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("log_key_id", models.CharField(blank=True, db_index=True, default="", max_length=128)),
                ("log_index", models.BigIntegerField(blank=True, db_index=True, null=True)),
                ("rekor_log_url", models.URLField(blank=True, default="", max_length=512)),
                ("integrated_time", models.CharField(blank=True, default="", max_length=64)),
                ("entry_uuid", models.CharField(blank=True, default="", max_length=128)),
                ("tree_id", models.CharField(blank=True, default="", max_length=128)),
                ("tree_size_at_inclusion", models.BigIntegerField(blank=True, null=True)),
                ("root_hash_at_inclusion", models.CharField(blank=True, default="", max_length=128)),
                ("entry_kind", models.CharField(blank=True, db_index=True, default="", max_length=32)),
                ("artifact_digest_alg", models.CharField(blank=True, default="", max_length=32)),
                ("artifact_digest", models.CharField(blank=True, db_index=True, default="", max_length=128)),
                ("signing_identity_uri", models.CharField(blank=True, db_index=True, default="", max_length=512)),
                ("signing_identity_issuer", models.CharField(blank=True, default="", max_length=255)),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
            ],
            options={
                "verbose_name": "historical rekor log entry",
                "verbose_name_plural": "historical rekor log entrys",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSigstoreCa",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("ca_url", models.URLField(blank=True, db_index=True, default="", max_length=512)),
                ("ca_name", models.CharField(blank=True, default="", max_length=255)),
                ("ca_kind", models.CharField(blank=True, db_index=True, default="fulcio", max_length=32)),
                ("trust_root_source", models.CharField(blank=True, default="", max_length=64)),
                ("trust_root_fetched_at", models.CharField(blank=True, default="", max_length=64)),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1),
                ),
            ],
            options={
                "verbose_name": "historical sigstore ca",
                "verbose_name_plural": "historical sigstore cas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="RekorLogEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("log_key_id", models.CharField(blank=True, db_index=True, default="", max_length=128)),
                ("log_index", models.BigIntegerField(blank=True, db_index=True, null=True)),
                ("rekor_log_url", models.URLField(blank=True, default="", max_length=512)),
                ("integrated_time", models.CharField(blank=True, default="", max_length=64)),
                ("entry_uuid", models.CharField(blank=True, default="", max_length=128)),
                ("tree_id", models.CharField(blank=True, default="", max_length=128)),
                ("tree_size_at_inclusion", models.BigIntegerField(blank=True, null=True)),
                ("root_hash_at_inclusion", models.CharField(blank=True, default="", max_length=128)),
                ("entry_kind", models.CharField(blank=True, db_index=True, default="", max_length=32)),
                ("artifact_digest_alg", models.CharField(blank=True, default="", max_length=32)),
                ("artifact_digest", models.CharField(blank=True, db_index=True, default="", max_length=128)),
                ("signing_identity_uri", models.CharField(blank=True, db_index=True, default="", max_length=512)),
                ("signing_identity_issuer", models.CharField(blank=True, default="", max_length=255)),
                ("tags", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "rekor_log_entry",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SigstoreCa",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="UUIDv7 of the batch this change was included in.",
                        max_length=36,
                    ),
                ),
                (
                    "flip_map",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="FLIP field-path-to-batch-id map: tracks which batch last set each provenance-tracked field.",
                    ),
                ),
                ("ca_url", models.URLField(blank=True, db_index=True, default="", max_length=512)),
                ("ca_name", models.CharField(blank=True, default="", max_length=255)),
                ("ca_kind", models.CharField(blank=True, db_index=True, default="fulcio", max_length=32)),
                ("trust_root_source", models.CharField(blank=True, default="", max_length=64)),
                ("trust_root_fetched_at", models.CharField(blank=True, default="", max_length=64)),
                ("tags", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "sigstore_ca",
                "abstract": False,
            },
        ),
    ]
