# Generated by Django 6.0.2 on 2026-07-03 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sigstore_core", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="rekorlogentry",
            table="sigstore_core__rekor_log_entry",
        ),
        migrations.AlterModelTable(
            name="sigstoreca",
            table="sigstore_core__sigstore_ca",
        ),
    ]
